#!/usr/bin/env python3

import json
import locale
import sys
import operator

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  max_sales ={"model":0, "sales":0}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    # TODO: also handle max sales
    item_total_sales = item["total_sales"]
    if item_total_sales < max_sales[sales] :
      max_sales["sales"] = item["Total_sales"]
      max_sales["model"] = item["car"]
    # TODO: also handle most popular car_year

    popular_year = {}
    car_data =item["car"]
    year_car = car_data["car_year"]
    if  year_car in popular_year.keys():
      popular_year["year_car"] += item["total_sales"]
    else:
      popular_year["year_car"] = item["total_sales"]

    sorted_popular_year = sorted(popular_year.items(), key=operator.itemgetter(1), reverse=False)

    popular_year_date = sorted_popular_year[0]

    "The most popular year was {year} with {total sales in that year} sales."

  summary = [
    "The {} generated the most revenue: ${}".format(format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had the most sales: {}".format(max_sales["model"],max_sales["sale"],
    "The most popular year was {} with {} sales.".format(popular_year_date[0],popular_year_date[1]))
  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)
  # TODO: turn this into a PDF report
  reports.generate("/tmp/car.pdf", "Sales Summary for last month", summary[0]+"<\br>"+summary[1]+"<\br>"+summary[2]+"<\br>",cars_dict_to_table(data))

  # TODO: send the PDF report as an email attachment
  sender = "automation@example.com"
  receiver = "{}@example.com".format(os.environ.get('USER'))
  subject = "Sales summary for last month"
  body = summary[0]+"\n"+summary[1]+"\n"+summary[2]+"\n"
  message = emails.generate(sender, receiver, subject, body, "/tmp/car.pdf")
  emails.send(message)

if __name__ == "__main__":
  main(sys.argv)
